[package]
name = "solverforge-solver"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Solver engine for SolverForge"
autobenches = false

[features]
default = []

[dependencies]
solverforge-core = { version = "0.19.4", path = "../solverforge-core" }
solverforge-scoring = { version = "0.19.4", path = "../solverforge-scoring" }
solverforge-config = { version = "0.19.4", path = "../solverforge-config" }
thiserror.workspace = true
tracing.workspace = true
rand.workspace = true
rand_chacha.workspace = true
rayon.workspace = true
smallvec.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["sync"] }
